# Generated by Django 2.1.2 on 2018-10-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wbs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.WBS', verbose_name='WBS'),
        ),
    ]
