# Generated by Django 2.1.2 on 2018-10-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181017_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDS',
            new_name='ProjectDeliverableSchema',
        ),
    ]
