# Generated by Django 2.1.2 on 2018-10-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181022_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='modelcreated',
            new_name='sructurecreated',
        ),
    ]
