# Generated by Django 2.1.2 on 2018-10-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20181022_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sructurecreated',
        ),
        migrations.AddField(
            model_name='project',
            name='sructure',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
