# Generated by Django 2.1.2 on 2018-10-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20181022_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='sructure',
            new_name='structure',
        ),
    ]
