# Generated by Django 2.1.2 on 2018-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20181023_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='isoname',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
