# Generated by Django 2.1.2 on 2018-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_region_isoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='isotype',
            field=models.CharField(choices=[('AR', 'Región autónoma'), ('DE', 'Departamento'), ('IR', 'Región indigena'), ('PR', 'Provincia')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='region',
            name='isoname',
            field=models.CharField(max_length=6),
        ),
    ]
